server:
  port: 9305
spring:
  application:
    name: admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:9301 #配置admin-server地址
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露Actuator的监控端点
  endpoint:
    health:
      show-details: always #显示健康的详细信息
    env:
      show-values: always #默认Actuator的环境变量会以****显示，这里开启显示
    configprops:
      show-values: always #默认Actuator的配置属性会以****显示，这里开启显示
    info:
      enabled: true
logging:
  file:
    name: admin-client.log #配置日志文件名称，使用Admin的日志监控必须配置