server:
  port: 9201
spring:
  profiles:
    active: dev
  application:
    name: micro-knife4j-gateway
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes: #配置路由路径
        - id: user-service
          uri: lb://micro-knife4j-user
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://micro-knife4j-order
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
knife4j:
  gateway:
    enabled: true
#    strategy: manual #网关文档聚合方式：手动配置路由
#    routes:
#      - name: user-service #分组名称
#        service-name: micro-knife4j-user #服务名称
#        url: /user-service/v3/api-docs?group=default  #OpenAPI数据源加载url地址
#        context-path: /user-service #服务对应网关的API路径
#      - name: order-service
#        service-name: micro-knife4j-order
#        url: /order-service/v3/api-docs/default
#        context-path: /order-service
    strategy: discover #网关文档聚合方式：服务发现（自动聚合）
    discover:
      version: openapi3 #配置OpenAPI3规范
      enabled: true #配置开启服务发现
    tags-sorter: order #配置tag排序规则
    operations-sorter: order #配置operation排序规则