## spring cloud config [server]


# spring config
spring:
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server

## spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8088/eureka/